---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

environment:
  DOCKER_BUILDKIT: "1"

steps:
  - name: docker
    image: plugins/docker
    settings:
      auto_tag: true
      build_args:
        - BUILDKIT_INLINE_CACHE=1
      password:
        from_secret: docker_password
      repo: noiseblend/api
      username: alinpanaitiu
      purge: false
      cache_from:
        - noiseblend/api:latest

  - name: deploy
    image: curlimages/curl
    commands:
      - curl -L -s -S https://alin:$${DEPLOY_PASSWORD}@deploy.darkwoods.win/noiseblend
    environment:
      DEPLOY_PASSWORD:
        from_secret: deploy_password
    when:
      branch:
        - master
    depends_on:
      - docker

  - name: cloudflare
    image: jetrails/drone-cloudflare-caching
    settings:
      api_token:
        from_secret: cloudflare_cache_purge_token
      zone_identifier: 4261720d9ab40fdc12b31ba8c63d6fdf
      action: purge_everything
    when:
      branch:
        - master
    depends_on:
      - deploy

---
kind: signature
hmac: 09e9fc22c6dd5efca796fb63a11d4088f13d8fabad47ed9246790d58b0b3e38b

...
