repos:
- repo: https://github.com/psf/black
  rev: 21.5b1
  hooks:
  - id: black
    language_version: python3.8
- repo: https://github.com/asottile/seed-isort-config
  rev: v2.1.0
  hooks:
  - id: seed-isort-config
    args: [--exclude=tests/.+\.py]
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
  - id: isort
- repo: local
  hooks:
  - id: pylint
    name: pylint
    stages: [push]
    entry: pylint
    language: system
    types: [python]
  - id: drone-lint-fmt-sign
    name: Validate Drone configuration
    language: system
    files: .drone.yml
    entry: sh -c 'drone lint; drone sign --save Noiseblend/api'
    stages: [commit]
