language: python
dist: xenial
python: "3.7"
cache:
  pip: true
services:
  - docker
matrix:
  include:
    - install:
        - sudo apt-get -qq update
        - sudo apt-get install -y libasound2-dev
        - pip install -r requirements-dev.txt
      script:
        - pylint noiseblend_api
    - install:
        - echo "$DOCKER_PASSWORD" | docker login -u alinpanaitiu --password-stdin
        - docker build -t noiseblend/api:$TRAVIS_COMMIT .
        - docker build -t noiseblend/api:latest .
      script:
        - docker images
deploy:
  provider: script
  script: bash scripts/docker_push.sh
  on:
    repo: Noiseblend/api
    all_branches: true
env:
  global:
    secure: gc27yy7/tdHDWFduzD2VtO9JvrIFOT4lKhfKQuR3H5+iavFMURSgvGENT9tzp81Ieb89ElXZqXF8cbsnTiLOKju6rbvQObU3dco83z1wMIui7hyosLBPbnUShSH+/4x7q3xIyL319eqc8c+OIW/PQbQC3YjMurV/Sy5n6gYqigq7VrMTymv9sFy278GzxdRT20TUd37NTOmBWqUlWr3Lcl/XTQFGgoC44UOLDJzRGTCUUEmcMUQMOQy1hwvlJtq3MlLcOWcMGLMaisrXfGvqHhVPW01sj872o2ndgqIsIL6B1FFE5y0yS4Uy1akNMpBHbxg4B/eEXWrMR2iwL7BgHNGXZx14HvMxl1yUcxH98Tr53Tv9lp3aLIx1VxpDQqVNXO8VZxkrQfJ7W8xPZDlcg5092peP6tAziwX+FsE9DVoRMDJyClbdfHqmy1L4w3PP+hyXSdgKHAkPrPQoUhHptY9AsVjs1QsQ5+FenWo1F1M0R70DT0E8R/ALy4JzoXXZ6tlxwdhg1lpsItq2fhO165EGUOJ9+P9G7XTR2Z/5227UgKqgUiFWZoY3jobis8wMuCVHfVIY+/u27bGzinodkL6NghkSB7gPuQkx5NitqeOBi9lUergjTv4QZv9vOIepSzRhH/XUXF3Lv2yhjjHY/It5NdFeQslxN175Awnww/8=
