FROM python:3.7

VOLUME /cache

COPY requirements.txt /
RUN pip install -U pip
RUN pip install --cache-dir /cache -r /requirements.txt

WORKDIR /app

CMD pip install --cache-dir /cache -e /spfy && \
    pip install --cache-dir /cache -e . && \
    python -m noiseblend_api.api
