[spotify]
client_id = ""
client_secret = ""
redirect_uri = "http://localhost:3000"
scope = [
    "user-read-email",
    "user-read-private",
    "user-read-birthdate",
    "user-library-read",
    "user-library-modify",
    "user-top-read",
    "user-modify-playback-state",
    "user-read-playback-state",
    "user-read-currently-playing",
    "user-read-recently-played",
    "playlist-read-private",
    "playlist-read-collaborative",
    "playlist-modify-public",
    "playlist-modify-private",
    "ugc-image-upload"
]

[api]
cors = true
allow_origins = ["http://localhost:3000"]

[db]
create_tables = true

[db.connection]
user = "postgres"
password = ""
host = "localhost"
database = "postgres"
port = 5432

[db.pool]
min_size = 2
max_size = 20
max_inactive_connection_lifetime = 300.0

[sendgrid]
template_id = ""
apikey = ""
sender = ""

[sentry]
dsn = ""
release = "dev"
environment = "development"

[redis.pool]
minsize = 5
maxsize = 50
[redis.auth]
host = "localhost"
port = 6379

[alexa]
auth_type = 'basic'
client_id = 'alexa-blend'
client_secret = 'alexa-secret'